### ISSUE TITLE
ember-data master Rollup build error

### ISSUE THREAD

**Issue by xg-wang** [tomdale/ember-cli-addon-tests#199] opened 2018-11-22 07:58 UTC
```
23:51:45 in ember-cli-fastboot on  master [!] is 📦 v2.0.0 via 🐹 3.3.0 took 40s
[I] ➜ yarn test
yarn run v1.10.1
$ mocha && ember test


  rewriting HTML
    1) builds an index.html that points to the browser build
cleaning up...

Build failed.

Build Error (Rollup)


Could not resolve './references/record' from tmp/rollup-cache_path-23iVf97F.tmp/build/-private/system/references.js
```

Also failed a new kicked travis-ci https://travis-ci.com/xg-wang/ember-cli-fastboot/jobs/160253348

**Comment by xg-wang** [comment] 2018-11-22 08:05
Some commit in ember-data#master caused this, I don't see this error yesterday.
cc @runspired @kellyselden

**Comment by kellyselden** [comment] 2018-11-22 12:54
Can we close this since it's not an issue here?

**Comment by runspired** [comment] 2018-11-22 12:56
We don’t know it’s not an issue here, only that apparently ember-data master and here are not compatible. Both do weird build things.

**Comment by kellyselden** [comment] 2018-11-22 12:59
OK thanks for the heads up.

**Comment by igorT** [comment] 2018-11-28 00:57
https://github.com/emberjs/data/pull/5757 is the commit which broke it

**Comment by runspired** [comment] 2018-11-28 00:59
I've confirmed that new apps using ember-data master do not break due to the above ember-data commit, only things using `ember-cli-addon-tests`, so it's not necessarily a fundamental issue with how ember-data is configured to build / publish: it may be an issue with how this repo is consuming it.

**Comment by runspired** [comment] 2018-11-28 01:18
**Update:** We don't fail when installing canary via `yarn`, but we DO fail on a new app when installing canary via `npm`.

**Comment by igorT** [comment] 2018-11-28 01:45
Should be fixed now

**Closed** 2018-11-28 02:08 UTC
